name: soulforge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.11
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.9.0
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.25.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/images/icons/

  fonts:
    - family: Bitter
      fonts:
        - asset: lib/assets/fonts/Bitter/Bitter-Regular.ttf
        - asset: lib/assets/fonts/Bitter/Bitter-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Bitter/Bitter-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
