name: soulforge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.2
  fluttertoast: ^8.2.10
  flutter_localizations:
    sdk: flutter
  intl: any
  sqlite3: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
